services:
  db:
    image: mysql:8.4
    container_name: final_project_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "s31122546"
      MYSQL_DATABASE: "final_project_db"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=db          # ‚Üê Change from "mysql" to "db" 
    ports:
      - "8080:80"
    depends_on:
      - db       

  nginx:
    image: nginx:alpine
    container_name: final_project_nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Main port for all services
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./ssl:/etc/ssl/private:ro
      - ./certbot-webroot:/var/www/certbot:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - phpmyadmin             

volumes:
  db-data:
    driver: local